export default {
    "label": "Blog: Composer",
    "id": "blog-composer",
    "parent": "blog",
    "summary": "This tag is used for creating new blog post",
    "specs": [],
    "otherAttributes" : {
        "titlePlaceholder":"Enter your post title here...",
      "saveLinkText" : "Save",
      "savedLinkText" : "Saved",
      "publishLinkText" : "Publish",
      "unpublishLinkText" : "Unpublish",
      "loginButtonText" : "Login to start a post",
      "dummyUserText" : "Unnamed",
      "dummyContentText" : "Dummy content...",
      "linkPromptText":"Enter the link URL",
      "imagePromptText":"Enter the image URL",
      "editProgessText" : "Saving...",
      "editErrorText":"Couldn't be saved!",
      "publishProgressText" : "Publishing...",
      "publishErrorText" : "Couldn't be published!",
      "unpublishProgressText" : "unPublishing...",
      "unpublishErrorText" : "Couldn't be unpublished!",
      "titleLengthErrorText" :"Title is too short.",
      "postLengthErrorText" : "Blog post cannot be empty.",
      "authorBeforeText" : "by",
      "createdTimeBeforeText" : "Created on",
      "editTimeBeforeText" : "Last edited on"
    }
}