export default {
    "label": "showBlogPost",
    "id": "showBlogPost",
    "parent": "show",
    "summary": "A javascript call to display a Blog Post",
    "specs": [{
        "type": "text",
        "key": "id",
        "label": "Id",
        "placeholder": "Identification number is required",
        "value": "5a5b77c638fe706999a9f65c8820f6b1"
    }],
    "otherAttributes" : {
      "noPostText":"This post is no longer available!",
      "editLinkText":"Edit",
      "publishLinkText" : "Publish",
      "unpublishLinkText" : "Unpublish",
      "deleteLinkText":"Delete",
      "saveLinkText" : "Save",
      "unknownUserText":"Unknown User",
      "replyText":"reply",
      "repliesText":"replies",
      "replyComposerText":"Write a Reply",
      "replyInputPlaceholder":"Write your reply here...",
      "replyButtonText" : "Send Reply",
      "clearButtonText" : "Clear",
      "loginButtonText" : "Login to write a reply",
      "publishProgressText" : "Publishing...",
      "publishErrorText" : "Couldn't be published!",
      "unpublishProgressText" : "unPublishing...",
      "unpublishErrorText" : "Couldn't be unpublished!",
      "deleteConfirmationText" : "Are you sure to delete this blog post?",
      "deleteProgressText" : "Deleting...",
      "deleteErrorText" : "Couldn't be deleted!",
      "replyDeleteConfirmation" : "Are you sure to delete this reply?",
      "postDeleteConfirmation" : "Are you sure to remove this post?",
      "commentTimeNowText" : "Now",
      "commentTimeSecondsText" : "%s second(s) ago",
      "commentTimeMinutesText" : "%s minute(s) ago",
      "commentTimeHoursText" : "%s hour(s) ago",
      "commentTimeDaysText" : "%s day(s) ago",
      "commentTimeWeeksText" : "%s week(s) ago",
      "commentTimeMonthsText" : "%s month(s) ago",
      "commentTimeYearsText" : "%s year(s) ago",
      "authorBeforeText" : "by",
      "publishedTimeBeforeText" : "Published in",
      "editTimeBeforeText" : "Last edited on"
    }
}